version: "3"
services:
    php-cli:
        build: ./builds/php-cli
        volumes:
            - .:/var/www
            - /mnt/c/Users/axele/php-projects/api-scratch/builds
            - /mnt/c/Users/axele/php-projects/api-scratch/vendor
            - /mnt/c/Users/axele/php-projects/api-scratch/.idea

    nginx-php:
        build: ./builds/nginx
        ports: 
            - "80:80"
        depends_on: 
            - php-language    
        volumes: 
            - .:/var/www
            - /mnt/c/Users/axele/php-projects/api-scratch/builds
            - /mnt/c/Users/axele/php-projects/api-scratch/vendor
            - /mnt/c/Users/axele/php-projects/api-scratch/.idea
    
    php-language:
        build: ./builds/php-fpm
        volumes: 
            - .:/var/www
            - /mnt/c/Users/axele/php-projects/api-scratch/vendor
            - /mnt/c/Users/axele/php-projects/api-scratch/.idea

    database:
        image: mysql:8.0.20
        environment:
             - MYSQL_ROOT_PASSWORD=123456789
        ports:
            - "3306:3306"
        volumes:
            - /home/axele/bd-files/mysql-files:/var/lib/mysql
            - /home/axele/bd-files/mysql-exports:/usr/src

networks:
    default:
        external:
            name: php-network