version: "3"
services:
    php-cli:
        image: php:7.4-cli
        volumes:
            - .:/var/www
            - /mnt/c/Users/axele/php-projects/api-scratch/builds
            - /mnt/c/Users/axele/php-projects/api-scratch/vendor
            - /mnt/c/Users/axele/php-projects/api-scratch/.idea

    nginx-php:
        build: ./builds/nginx
        ports: 
            - "80:80"
        depends_on: 
            - php-language    
        volumes: 
            - .:/var/www
            - /mnt/c/Users/axele/php-projects/api-scratch/builds
            - /mnt/c/Users/axele/php-projects/api-scratch/vendor
            - /mnt/c/Users/axele/php-projects/api-scratch/.idea
    
    php-language:
        image: php:7.4-fpm
        volumes: 
            - .:/var/www
            - /mnt/c/Users/axele/php-projects/api-scratch/vendor
            - /mnt/c/Users/axele/php-projects/api-scratch/.idea


networks:
    default:
        external:
            name: php-network